Repository ezsystems/ezplatform, pull requests merged in 2019-03, with the labels that each got.

#349 EZP-30170: [2.5LTS] Drop Varnish 4 + get rid of duplicated VCL in meta repo
  doc/varnish/varnish.md
  doc/varnish/vcl/varnish4_xkey.vcl
Labels: Ready for QA

#366 EZP-30208: Add ezsystems/ezplatform-graphql to meta repositories
  app/AppKernel.php
  app/config/routing.yml
  app/config/routing_dev.yml
  composer.json
Labels: Improvement, Ready for review

#365 EZP-29938: Enabled PostgreSQL support via DoctrineSchemaBuilder
  app/AppKernel.php
  app/config/config.yml
  app/config/default_parameters.yml
  app/config/parameters.yml.dist
  composer.json
Labels: Feature, QA approved

#370 EZP-30318: [DX] Simplified ezplatform.yml to avoid duplicated config
  .travis.yml
  app/config/ezplatform.yml
Labels: Bug, Improvement, Ready for QA

#372 EZP-30302: Webpack encore generates assets in wrong directory on Windows
  composer.json
Labels: Bug, QA approved, Ready for review

#378 EZP-30345: Cannot override webpack encore JS/CSS from bundle
  ez.webpack.config.js
  webpack.config.js
Labels: Bug, QA approved

#379 EZP-30363: Provide default Content Tree configuration in meta repositories
  app/config/ezplatform.yml
Labels: Improvement, Ready for review
