Repository ezsystems/ezplatform, pull requests merged in 2019-10, with the labels that each got.

#459 [symfony4] Use correct logs dir
  .dockerignore
  .gitignore
  bin/.ci/prepare_archive.sh
  bin/.travis/trusty/setup_from_external_repo.sh
  doc/docker/Dockerfile-app
  doc/docker/install_script.sh
  var/log/.gitkeep
Labels: 3.x

#455 Docker on 3.x
  .env
  doc/docker/install-dependencies.yml
  doc/docker/install_script.sh
Labels: 3.x

#461 EZP-30376 [Travis] Implementing reporting tool to behat automated tests
  .travis.yml
  behat.yml.dist
  bin/.travis/rsa_allure.enc
  composer.json
Labels: Ready for MERGE

#472 Added comment to `ezpublish_rest.csrf_token_intention` to avoid authentication issues
  app/config/config.yml
Labels: Improvement, Ready for review

#469 EZP-30985: Added eZ user checker to security config
  config/packages/security.yaml
Labels: Improvement, QA approved

#470 [Docker] Allowed to set PHP memory limit through env
  doc/docker/base-dev.yml
  doc/docker/base-prod.yml
Labels: Ready for MERGE
