Repository ezsystems/ezplatform, pull requests merged in 2019-08, with the labels that each got.

#441 EZP-30804: Removed env use from session handler configuration
  config/packages/ezplatform.yaml
  config/packages/framework.yaml
Labels: Bug, QA approved

#436 EZP-30662: Added http cache tests
  behat.yml.dist
Labels: Ready for MERGE

#443 [Behat] Marked Behat env as test
  config/packages/behat/framework.yaml
Labels: Ready for MERGE

#440 [Behat] Increased success notification timeout in Behat env
  app/config/ezplatform_behat.yml
Labels: Ready for MERGE

#447 [Travis] Increased default Composer memory limit
  .env
Labels: Ready for review

#448 [Composer] Increased BehatBundle version
  composer.json
Labels: Ready for review

#449 EZP-30714: Fixed default Webpack Encore configuration
  config/packages/ezplatform_assets.yaml
  config/packages/webpack_encore.yaml
Labels: Bug, QA approved

#446 EZP-30809: changed notification timeout for behat
  config/packages/behat/ezplatform.yaml
Labels: Improvement, Ready for review
