Repository ezsystems/ezplatform, pull requests merged in 2019-06, with the labels that each got.

#410 Use old Docker-Selenium container
  .env
Labels: Ready for MERGE

#411 EZP-30644: Duplicated database configuration in .env
  .env
Labels: Bug, Ready for review

#412 EZP-30655: Package ezsystems/ezplatform-cron is missing from OSS
  composer.json
  config/bundles.php
Labels: Bug

#414 EZP-30657: Upgrade `ezsystems/ezplatform-matrix-fieldtype` to use Symfony 4 components
  composer.json
  config/bundles.php
Labels: Improvement

#415 [Travis] Increase Composer memory limit to 4g
  .env
Labels: Ready for review

#413 EZP-30642: Added Travis dedicated error log
  app/config/config_behat.yml
Labels: Ready for review

#408 EZEE-2800: Switched to use scssphp/scssphp dependency
  app/config/config.yml
  composer.json
Labels: QA approved

#418 EZP-30695: Configured subtree paths for AdminUI
  app/config/ezplatform.yml
Labels: Improvement, QA approved, Ready for review
