Repository ezsystems/ezplatform, pull requests merged in 2019-09, with the labels that each got.

#453 EZP-30906: Removed deprecated templating component integration
  config/packages/ezplatform.yaml
Labels: Improvement, QA approved, Ready for MERGE

#458 Added graphql schema generation after database install
  bin/.travis/trusty/setup_ezplatform.sh
Labels: Ready for MERGE

#451 EZP-30884: Added Travis setup
  .travis.yml
Labels: Ready for MERGE

#442 EZP-30816: [3.0] Support for Platform.sh
  .platform.app.yaml
  .platform/routes.yaml
  .platform/services.yaml
  .platform/varnish.vcl
  composer.json
  config/packages/000-platformsh.php
  config/packages/cache_pool/cache.memcached.yaml
  config/packages/cache_pool/cache.redis.yaml
  config/packages/cache_pool/cache.tagaware.filesystem.yaml
Labels: Ready for MERGE

#460 GraphQL schema generator in installer + p.sh directory
  .platform.app.yaml
  composer.json
Labels: Ready for MERGE

#444 [Platform.sh] Revise bundled config & inline doc
  .platform.app.yaml
  .platform/services.yaml
  app/config/config.yml
  app/config/default_parameters.yml
  app/config/parameters.yml.dist
  bin/platformsh/pre_start-per_node-clear_cache.sh
  doc/platformsh/INSTALL.md
  doc/platformsh/README.md
Labels: Ready for MERGE

#463 EZP-30636: Enabled eZ Platform Bundle
  config/bundles.php
  config/packages/behat/ezplatform.yaml
  config/packages/dfs/dfs.yml
  config/packages/ezplatform.yaml
  config/packages/ezplatform_admin_ui.yaml
  config/packages/security.yaml
Labels: 3.x, Feature, QA approved
