Repository ezsystems/ezplatform, pull requests merged in 2019-07, with the labels that each got.

#424 EZEE-2802: Renamed ezplatform_kernel.yaml -> ezplatform.yaml to change loading order
  config/routes/ezplatform.yaml
Labels: Bug, Ready for review

#421 EZP-30693: Enabled SOLR Search Engine configuration
  .env
  config/packages/ezplatform_solr.yaml
Labels: Improvement, QA approved

#425 EZP-30656: render_esi is not configured by default
  config/packages/ezplatform.yaml
  config/packages/framework.yaml
Labels: Bug, Ready for review

#428 EZP-30667: eZ Platform 3.0 does not support PostgreSQL setup
  .env
Labels: Bug, Ready for review

#426 Enabled ezplatform-graphql
  composer.json
  config/bundles.php
  config/packages/graphql.yaml
  config/routes/dev/graphiql.yaml
  config/routes/graphql.yaml
Labels: QA approved

#434 EZP-30667: Made database charset and collation configurable via dotenv
  .env
  config/packages/doctrine.yaml
Labels: Bug

#417 Add support for Chromium driver
  .env
  behat.yml.dist
  composer.json
  doc/docker/README.md
  doc/docker/chromium.yml
Labels: Ready for MERGE
