Repository ezsystems/ezplatform, pull requests merged in 2019-04, with the labels that each got.

#383 EZP-30412: Composer is always using dev for generating encore assets
  bin/compile_assets.sh
  composer.json
Labels: Bug, QA approved

#382 EZP-30406: Cannot add custom webpack config from bundle
  .gitignore
  ez.webpack.custom.configs.js
  var/encore/.gitkeep
  webpack.config.js
Labels: Bug, Ready for QA

#356 EZP-30098 [Travis] Implement solution for running tests in threads based on fastest
  .travis.yml
  behat.yml.dist
  bin/.travis/get_behat_features.sh
  composer.json
Labels: Ready for QA, Ready for review

#393 EZP-30479: Compile assets script is not working on some setups
  bin/compile_assets.sh
  composer.json
Labels: Bug
