Repository ezsystems/ezplatform, pull requests merged in 2019-05, with the labels that each got.

#401 EZP-30315 [Travis] Standarize and clean up travis configurations across the repositories
  .travis.yml
Labels: Ready for review

#402 EZP-30539: Move Platform Behat Bundle to BehatBundle
  app/AppKernel.php
  app/config/routing_behat.yml
  behat.yml.dist
Labels: Ready for MERGE

#399 EZP-28034: Enabled eZ Platform REST bundle
  app/AppKernel.php
  app/config/routing.yml
  behat.yml.dist
  composer.json
Labels: Feature, QA approved, Ready for MERGE

#403 [Travis] Set REST Bundle tests to run directly from its package
  .travis.yml
  bin/.travis/run_rest_tests.sh
Labels: Bug, Work in progress
