Repository ezsystems/ezplatform, pull requests merged in 2019-12, with the labels that each got.

#479 EZP-29112: Implemented scenarios for Site Access matching
  behat.yml.dist
  doc/docker/README.md
  doc/docker/multihost.yml
Labels: Ready for MERGE

#482 EZP-31189: Reduce memory required for 1.7 and 1.13 branches to install
  composer.json
Labels: Ready for review

#486 [Travis] Increased Composer memory limit for install
  .env
Labels: Ready for review

#485 EZEE-2928: [Behat] Changed debug value to true for Symfony2Extention
  behat.yml.dist
Labels: Ready for MERGE

#489 EZP-30836: Changed default cache adapter to filesystem based
  .env
  config/packages/cache_pool/cache.memcached.yaml
  config/packages/cache_pool/cache.redis.yaml
  config/packages/cache_pool/cache.tagaware.filesystem.yaml
  config/packages/ezplatform.yaml
Labels: Improvement, Ready for review

#484 EZP-31239: [DX] Reduce amount of generated debug data / dev overhead by default
  app/config/config_dev.yml
Labels: QA approved
