Repository ezsystems/ezplatform, pull requests merged in 2019-11, with the labels that each got.

#476 EZP-31092 Adapt report sending method to changes in server accessing
  bin/.travis/rsa_allure
Labels: Ready for MERGE

#478 EZP-31132: [Composer] Explicitly required monolog/monolog:^1.25.2
  composer.json
Labels: Bug

#475 EZP-30837: Migrate from repository-forms to ezplatform-content-forms package
  .travis.yml
  behat.yml.dist
  composer.json
  config/bundles.php
  config/routes/ezplatform_content_forms.yaml
  config/routes/ezplatform_repository_forms.yaml
Labels: Improvement, Work in progress

#480 EZP-30769: Registered missing translations commands
  config/services.yaml
Labels: Bug, QA approved
