Repository ezsystems/ezplatform, pull requests merged in 2020-12, with the labels that each got.

#626 EZP-32214: Refactored config/packages/overrides/* as Compiler Passes
  config/packages/overrides/generic.php
  config/packages/overrides/platformsh.php
  src/Kernel.php
Labels: Improvement, Ready for review

#627 EZP-31594: Replaced bin/console with original file from symfony/console recipe
  bin/console
Labels: Improvement

#624 Bumped Symfony to v5.2 and prepared packages for 3.3 release
  composer.json
Labels: Feature, Ready for review

#635 [Composer] Use branch alias for behatbundle
  composer.json
Labels: Ready for review

#632 EZP-32214: Removed forward incompatible PHP configuration files
  .env
  config/packages/ezplatform.yaml
  config/packages/ezplatform_solr.yaml
  config/packages/overrides/generic.php
  config/packages/overrides/platformsh.php
  src/Kernel.php
Labels: Improvement, Ready for review

#636 [Composer] Bumped Symfony to stable v5.2.1
  composer.json
Labels: 3.x, Feature, Work in progress

#637 Removed obsolete configuration of translation
  config/packages/ezplatform_admin_ui.yaml
Labels: Improvement, Ready for QA

#642 EZEE-3422: Prepared LICENSE and COPYRIGHT files for 3.3 release
  COPYRIGHT
  LICENSE
  LICENSE-bul
  README.md
Labels: Ready for review
