Repository ezsystems/ezplatform, pull requests merged in 2020-07, with the labels that each got.

#573 EZP-31650: Temporarily disable Trash test cases
  .travis.yml
Labels: Ready for review

#572 [Behat] Limited fastest version to ~1.6
  composer.json
Labels: Ready for review

#580 [Composer] Updated branch-alias for master
  composer.json
Labels: Ready for review

#586 [Docker] Added DATABASE_VERSION variable to install-dependencies
  doc/docker/install-dependencies.yml
Labels: Ready for MERGE, Ready for review

#583 EZP-31607: Fixed processing of default value of Varnish invalidate token
  .env
  config/packages/ezplatform.yaml
Labels: Bug, QA approved, Ready for review

#588 [Docker] Removed hardcoded -node and -dev image usages
  .env
  doc/docker/Dockerfile-app
  doc/docker/Dockerfile-distribution
  doc/docker/Dockerfile-nginx
  doc/docker/base-dev.yml
  doc/docker/install-dependencies.yml
Labels: Ready for review
