Repository ezsystems/ezplatform, pull requests merged in 2020-02, with the labels that each got.

#500 [Travis] Changed user running REST tests to root
  .travis.yml
Labels: Ready for review

#499 [Composer] Update ezplatform-http-cache to 1.0 & symfony-tools to 1.1
  composer.json
Labels: QA approved

#501 EZP-31377: Use imagick by default on Platform.sh to avoid memory issues
  app/config/config.yml
  app/config/default_parameters.yml
  app/config/env/platformsh.php
Labels: QA approved

#502 [Platform.sh] Updated Maria DB version to 10.4
  .platform/services.yaml
  composer.json
Labels: QA approved

#498 EZP-31313: Make Behat SiteAccess aware
  doc/docker/base-dev.yml
  doc/docker/base-prod.yml
Labels: Ready for MERGE

#504 EZP-31346: [Travis] Added script invoking script triggering regression build
  bin/.travis/trigger_regression_build.sh
Labels: Ready for review
