Repository ezsystems/ezplatform, pull requests merged in 2020-10, with the labels that each got.

#602 EZP-31982: Revert cache setting in Encore config to default
  config/packages/webpack_encore.yaml
Labels: Bug

#600 Added conflict with doctrine/dbal >= 2.11.0
  composer.json
Labels: Bug

#601 vhost.template: Update default APP_ENV from prod to dev
  doc/apache2/vhost.template
  doc/nginx/vhost.template
Labels: QA approved

#605 EZP-31875: Added firewall rules for JWT auth
  config/packages/security.yaml
Labels: QA approved

#606 EZP-32002: Move system information UI to be a part of ez-support-tools
  config/routes/ezplatform_support_tools.yaml
Labels: Improvement, Ready for review

#613 [Behat] Fixed FOB\SymfonyExtension configuration
  behat.yml.dist
Labels: Ready for review

#610 Aligned meta repository with Symfony recipes output
  .env.test
  assets/app.js
  assets/styles/app.css
  behat.yml.dist
  config/packages/prod/deprecations.yaml
  config/preload.php
  config/routes/dev/framework.yaml
  config/services_behat.yaml
  features/demo.feature
  templates/themes/standard/full/welcome_page.html.twig
  templates/themes/standard/pagelayout.html.twig
  webpack.config.js
Labels: Improvement

#616 EZP-32096: Added icon set configuration for Admin UI
  config/bundles.php
  config/packages/ezplatform_admin_ui.yaml
Labels: 3.x, Improvement, Ready for review

#617 EZP-32078: Bumped ezplatform-admin-ui-assets package version
  composer.json
Labels: Improvement

#597 EZP-31930: Improved output of `composer ezplatform-install` command
  composer.json
Labels: Improvement, QA approved, Ready for review

#592 EZP-31804: [Docker] Added fixed IP to varnish container to workaround TRUSTED_PROXIES setting
  doc/docker/varnish.yml
Labels: Ready for MERGE
