Repository ezsystems/ezplatform, pull requests merged in 2020-04, with the labels that each got.

#514 EZP-31519: Moved app.php rejection snippet from front controller to ezpublish-kernel
  doc/apache2/vhost.2.2.template
  doc/apache2/vhost.template
  doc/nginx/ez_params.d/ez_rewrite_params
  web/app.php
Labels: Improvement, Ready for review

#524 EZP-31535: Replated deprecated Symfony\Component\Debug\Debug class
  bin/console
Labels: Bug

#521 Changed APP_TRUSTED_PROXIES variable to TRUSTED_PROXIES
  bin/vhost.sh
  doc/apache2/vhost.template
  doc/docker/base-dev.yml
  doc/docker/base-prod.yml
  doc/docker/distribution.yml
  doc/docker/my-ez-app-stack.yml
  doc/docker/varnish.yml
  doc/nginx/vhost.template
Labels: Ready for MERGE

#529 Changed "welcome page" template and CSS so it fits on HD monitors in fullscreen without scrollbar.
  assets/scss/welcome-page.scss
  templates/themes/standard/full/welcome_page.html.twig
Labels: QA approved

#531 EZP-31550: [Behat] Added screenshot extensions
  behat.yml.dist
  composer.json
Labels: Ready for review

#535 [Docker] Changed install-dependencies to rely on PHP_IMAGE variable
  doc/docker/install-dependencies.yml
Labels: Ready for review

#532 [Behat] Added AllureFormatter configuration and allure-php-api direct requirement
  behat.yml.dist
  composer.json
Labels: Ready for review
