Repository ezsystems/ezplatform, pull requests merged in 2020-06, with the labels that each got.

#550 [Composer] Added conflict with symfony/framework-bundle 5.1.0
  composer.json
Labels: Ready for review

#551 Update cache_pool comment in ezplatform.yaml
  config/packages/ezplatform.yaml
Labels: Ready for review

#547 [Travis] Check if downloaded docker-compose is an application
  bin/.travis/trusty/update_docker.sh
Labels: Ready for review

#541 Platform.sh: allow to use HTTP access credentials for Varnish
  config/packages/overrides/platformsh.php
Labels: QA approved

#560 [Composer] Added direct requirement for doctrine/doctrine-migrations-bundle
  composer.json
Labels: Ready for review

#567 EZP-31688: Removed obsolete forked 3rd party packages
  composer.json
Labels: Ready for review

#570 Upgraded doctrine/migrations to ^3.0
  composer.json
  config/packages/doctrine_migrations.yaml
  migrations/.gitignore
Labels: Improvement

#543 Bring back SYMFONY_TMP_DIR (in another form) for Docker optimization
  src/Kernel.php
Labels: QA approved
