Repository ezsystems/ezplatform, pull requests merged in 2020-03, with the labels that each got.

#506 EZP-31483: Removed JMS Translation command service definitions
  config/services.yaml
Labels: Improvement, Ready for review

#505 [VCL] Update platform.sh VCL with config from ezplatform-http-cache
  .platform/varnish.vcl
  doc/varnish/varnish.md
  doc/varnish/vcl/parameters.vcl
  doc/varnish/vcl/varnish4_xkey.vcl
Labels: Ready for QA

#508 [Docker] Changed purge type to "varnish"
  doc/docker/varnish.yml
Labels: Ready for review

#510 EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel
  behat.yml.dist
  composer.json
  doc/i18n/handle_translation_in_contribution.md
Labels: Improvement, Rebase required, Work in progress

#517 Fixed incorrect link to discuss.ezplatform.com
  templates/themes/standard/full/welcome_page.html.twig
Labels: Bug
