Repository ezsystems/ezplatform, pull requests merged in 2020-09, with the labels that each got.

#594 [Composer] Reduce memory required for branch 1.13 to install
  .env
  composer.json
Labels: Ready for MERGE

#546 [Platform.sh] Changed default version of Solr to 7.7
  .platform/services.yaml
Labels: Ready for review

#596 EZP-31740: Fixed and migrated DFS configuration to Symfony 5
  config/packages/dfs/dfs.yaml
  config/packages/overrides/generic.php
  config/packages/overrides/platformsh.php
Labels: 3.x, Bug, QA approved

#593 EZP-31462: Add behat suite for ezplatform-user
  behat.yml.dist
Labels: Improvement, Ready for review
